# Generated by Django 4.1.1 on 2022-12-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcondition',
            name='doctor_id',
        ),
    ]
