# Generated by Django 4.1.1 on 2023-01-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_remove_patientcondition_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profilePicture',
            field=models.ImageField(default=None, null=True, upload_to='profilePictures'),
        ),
    ]
