# Generated by Django 4.1.1 on 2022-12-26 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('Patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diceaseCatagory_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Doctor.diceasecatagory'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='catagory_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctorcatagory'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
