# Generated by Django 4.1.1 on 2023-01-08 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 8, 22, 8, 56, 846272)),
        ),
    ]
