# Generated by Django 4.1.1 on 2023-01-08 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_prescription_prescription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
