# Generated by Django 4.1.1 on 2023-01-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_alter_prescription_prescription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profilePicture',
            field=models.ImageField(default=None, null=True, upload_to='profilePictures'),
        ),
    ]
